### ISSUE TITLE
Question/Issue

### ISSUE THREAD

**Issue by ish12321** [OpenGamePanel/OGP-Agent-Linux#20]
I've a ftp made other than that of ogp's.. The agent again and again resets that ftp which has access over everything and disallows it to see cs files in ogp user files folder/6/

**Comment by ish12321** [comment]
How to fix that?

**Comment by Zorrototo** [comment]
Open a thread in the forum instead of using the GitHub Issues for everything. Be sure to read the rules how to ask for help before random posting.

Support forum: https://www.opengamepanel.org/forum/viewforum.php?forum_id=2
Features request: https://www.opengamepanel.org/forum/viewforum.php?forum_id=4
