### ISSUE TITLE
Graceful gameserver shutdown

### ISSUE THREAD

**Issue by Megamezzomixer** [OpenGamePanel/OGP-Agent-Linux#27]
Hello everyone,

That is not a real issue, more a feature request.
I am running a Garry's Mod Dedicated Server on OGP.
Some of my addons installed on the server need a proper shutdown sequence to ensure no errors or file loss happens. For now I need to type "quit" into the console to shut it down properly and after around 5 seconds I terminate the screen session using the stop button on the panel.
Now, is it possible to create like a third option which properly shuts the server down and then kills the session afterwards?
I've experienced problems releated to a forced shutdown on Minecraft servers as well.

**Comment by own3mall** [comment]
There are the control protocols that attempt to shutdown the server gracefully using rcon.  If this is an option for the games you've mentioned, that's the way to do it.

https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/master/ogp_agent.pl#L1195

If the game doesn't support any of those protocols, you could extend the functionality so that it might. 

There's also a 5 second / user definable wait time to allow the server to gracefully shutdown for Arma3:

https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/master/ogp_agent.pl#L1244

We could apply it depending on the situation for other games as well... possibly.

**Comment by own3mall** [comment]
So, it looks like Garry's Mod should shutdown gracefully already since it is using the rcon2 protocol.  You can increase the amount of time it waits before terminating by adjusting your config variable:

http://opengamepanel.org/forum/viewthread.php?thread_id=5996

**Comment by own3mall** [comment]
Minecraft doesn't look like it has protocol support.

**Comment by Megamezzomixer** [comment]
To your first comment: Yes, Garry's Mod could use this technique. How can I enable that for me?

To the second: Minecraft can be controlled using rcon, but not with the "quit" command. For MC it's "stop".

**Comment by rocco27** [comment]
Yes Minecraft has RCON protocol, but the question is OGP has any compatible RCON protocol support for Minecraft...:)

**Comment by Megamezzomixer** [comment]
Even then, Minecraft is not my question here. How can I enable the graceful shutdown sequence for my Garry's Mod Server?  The protocol used in OGP seems to be compatible with Source servers?

**Comment by Zorrototo** [comment]
Have your admin password in the Control Password field when you edit it.

**Comment by own3mall** [comment]
Yes, and read the link I posted in this thread with helpful information regarding this feature.

**Comment by Megamezzomixer** [comment]
Alright. I'll have a look into that. Thanks, guys.
