### ISSUE TITLE
add backdoor fix.

### ISSUE THREAD

**Issue by PredatorFly** [OpenGamePanel/OGP-Agent-Linux#29]
AMXX on counter-strike servers, a user can see, modify and delete folders outside their default directory, for example, a script can be used in this way (rm ../../../../../usr/share/ogp_agent) and delete another HOME outside your user and my question: you can separate permissions of servers per user,
so block at all costs that the server itself has access to another route over your default HOME.

**Comment by Zorrototo** [comment]
Aren't you supposed to report this issues to AMXX if the issues comes from the plugin? maybe explain a clear case where you could do things with exact details?

**Comment by rocco27** [comment]
It is true. It is a know issue and can be exist in many game servers.

The most secure way will be hosting each game servers on a seperated users, however it also means need a lots of rework on OGP, I don't think devs can offer this right now. Maybe one day...

If you really want to host CS:GO with AMX, then you have to take the risk against bad customers. But don't forget, you can always defend yourself by use of term and they can accept or deny... ;)

**Comment by PredatorFly** [comment]
As Rocco says, if you can outwit this security with AMXX, nobody says that it can not be used with other servers, a friend added that protection, and it worked but in an old version of ogp_agent.pl but unfortunately I lost the file, I know that They were very big changes, they were only small modifications in 3 functions.

**Comment by own3mall** [comment]
Maybe if we ran the server startup scripts using rbash, that would help?

https://www.gnu.org/software/bash/manual/html_node/The-Restricted-Shell.html

Not sure what we could do for Windows... but regardless, this is a tricky situation to fix.  It's unfortunate that AMXX opens up this possibility.  It really should be something that is fixed in AMXX in my opinion.

**Comment by Zorrototo** [comment]
Not sure if that would fix AMXX problem but that sounds overall improvement if that changes nothing to how OGP works on Linux I'm always for an increase in security :+1:

**Comment by PredatorFly** [comment]
> Maybe if we ran the server startup scripts using rbash, that would help?
> 
> https://www.gnu.org/software/bash/manual/html_node/The-Restricted-Shell.html
> 
> Not sure what we could do for Windows... but regardless, this is a tricky situation to fix. It's unfortunate that AMXX opens up this possibility. It really should be something that is fixed in AMXX in my opinion.

I try, but I did not get much! Maybe something like that!
Suggested by Sugisaki:

`	$respawn_server_command .= "\n"
	. "echo ". $SUDOPASSWD . " | sudo -S -p \"\" sh -c 'useradd ". $screen_id . "'\n"
	. "sudo chattr -i ./". $server_exe . "\n"
	. "sudo chown -R ". $screen_id . " ". $home_path ." \n"
	. "sudo chmod -R 770 * \n"
	. "sleep 1 \n"
	. "sudo chattr +i ./". $server_exe . "\n"
	. "sudo -u ". $screen_id . " bash -c '". $exec_cmd. "'\n"
	. "exit\n"
	. "}" . "\n"
	. "startServer" . "\n";
`

**Comment by Zorrototo** [comment]
"I try, but I did not get much!" what does it mean? What did you try and what was the result?

**Comment by PredatorFly** [comment]
sorry for my bad english, try to modify permissions of the server when starting it following references of a friend, but I did not get anything at all.

**Comment by Zorrototo** [comment]
Still don't know what you did and what was the result. Too cryptic for me. Pass. :-1:

**Comment by own3mall** [comment]
No good solution at the moment.  Fix is to not allow user access to more than they should have.

**Comment by ghost** [comment]
**ATTENTION! DO NOT USE THIS SOFTWARE FOR PRODUCTION!**
It is not secure. This is probably not meant for production, and is only a experiment / test / learning project. A secure game hosting panel would run each game in their own container so no damage can be done to the system, even if the user installs a malicious plugin onto the game server, because it is isolated from the surroundings. And even inside the Docker container, the game server process should not run as root, but instead a low privilege user.

**Comment by own3mall** [comment]
You must be very scared.  There is a lot that happens to ensure that things are pretty secure.  Go pound sand and hide somewhere else.  The vulnerability mentioned in this issue is 3rd plugin party related.  Don't enable that service on your servers, and you shouldn't have problems.  A lot of people have the misconstrued idea that you can't have a secure shared hosting environment.  But, you actually can, so there you go.
